services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: localchat-backend
    ports:
      - "8080:8080"
    networks:
      - llm-net
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped


  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: localchat-frontend
    networks:
      - llm-net
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  llm-net:
    external: true
